openapi: 3.0.0
info:
  title: Contact Request Service
  version: '1.0'
  description: Contact Request Service

tags:
  - name: contact-request-controller
    description: Contact request controller

paths:
  /api/contact/requests:
    get:
      operationId: getContactRequestsByCriteria
      tags:
        - contact-request-controller
      summary: Get contact requests by criteria
      parameters:
        - in: query
          name: criteria
          required: true
          schema:
            $ref: '#/components/schemas/ContactRequestCriteria'
      responses:
        200:
          description: List of contact requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRequestList'
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/contact/requests/send:
    post:
      operationId: sendContactRequest
      tags:
        - contact-request-controller
      summary: Send a contact request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
      responses:
        204:
          description: Contact request sent
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/contact/requests/{requestId}/accept:
    post:
      operationId: acceptContactRequest
      tags:
        - contact-request-controller
      summary: Accept contact request
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Request accepted
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/contact/requests/{requestId}/decline:
    delete:
      operationId: declineContactRequest
      tags:
        - contact-request-controller
      summary: Decline contact request
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Request declined
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        403:
          $ref: 'common-types.yaml#/components/responses/Forbidden'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  schemas:
    CreateContactRequest:
      type: object
      properties:
        toUserId:
          type: integer
      required:
        - toUserId

    ContactRequest:
      type: object
      properties:
        id:
          type: integer
        fromUser:
          $ref: 'user-api.yaml#/components/schemas/ShortUser'
        toUser:
          $ref: 'user-api.yaml#/components/schemas/ShortUser'
        timeCreated:
          type: string
          format: date-time
      required:
        - id
        - fromUser
        - toUser
        - timeCreated

    ContactRequestList:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/ContactRequest'
      required:
        - total
        - items

    ContactRequestCriteria:
      allOf:
        - $ref: 'common-types.yaml#/components/schemas/BaseCriteria'
        - type: object
          properties:
            fromUserId:
              type: integer
            toUserId:
              type: integer
            minTimeCreated:
              type: string
              format: date-time
            maxTimeCreated:
              type: string
              format: date-time