openapi: 3.0.0
info:
  title: Contact Service - Contacts API
  version: '1.0'
  description: API for managing confirmed contacts

tags:
  - name: contact-controller
    description: Manages confirmed contacts

servers:
  - url: http://localhost:8080

paths:
  /api/contacts:
    get:
      tags:
        - contact-controller
      summary: Get all contacts of the current user
      operationId: getUserContacts
      responses:
        200:
          description: List of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

  /api/contacts/{secondUserId}:
    delete:
      tags:
        - contact-controller
      summary: Delete a contact between the current user and the given user
      operationId: deleteContact
      parameters:
        - name: secondUserId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Contact deleted
        400:
          $ref: 'common-types.yaml#/components/responses/BadRequest'
        401:
          $ref: 'common-types.yaml#/components/responses/Unauthorized'
        404:
          $ref: 'common-types.yaml#/components/responses/NotFound'
        500:
          $ref: 'common-types.yaml#/components/responses/InternalServerError'

components:
  schemas:
    Contact:
      type: object
      properties:
        firstUserId:
          type: integer
        secondUserId:
          type: integer
        firstCurrentDebt:
          type: number
          format: double
        secondCurrentDebt:
          type: number
          format: double
        firstHistoryDebt:
          type: number
          format: double
        secondHistoryDebt:
          type: number
          format: double
      required:
        - firstUserId
        - secondUserId
