package ua.edu.ukma.cyber.soul.splitfast.criteria;

import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import ua.edu.ukma.cyber.soul.splitfast.controllers.rest.model.GeoLabelCriteriaDto;
import ua.edu.ukma.cyber.soul.splitfast.domain.entitites.GeoLabelEntity;
import ua.edu.ukma.cyber.soul.splitfast.domain.entitites.GeoLabelEntity_; // Assuming this will be generated by JPA metamodel

import java.util.List;

public class GeoLabelCriteria extends Criteria<GeoLabelEntity, GeoLabelCriteriaDto> {

    public GeoLabelCriteria(GeoLabelCriteriaDto criteriaDto) {
        super(GeoLabelEntity.class, criteriaDto);
    }

    @Override
    protected <R> List<Predicate> formPredicates(Root<GeoLabelEntity> root, CriteriaQuery<R> query, CriteriaBuilder cb) {
        PredicatesBuilder<GeoLabelEntity> builder = new PredicatesBuilder<>(root, cb)
                .like(criteria.getName(), GeoLabelEntity_.name)
                .eq(criteria.getCreatorId(), GeoLabelEntity_.creatorId)
                .eq(criteria.getActivityId(), GeoLabelEntity_.activityId);

        return builder.getPredicates();
    }

    @Override
    protected void fetch(CriteriaBuilder cb, Root<GeoLabelEntity> root) {
        root.fetch(GeoLabelEntity_.creator);
        root.fetch(GeoLabelEntity_.activity);
    }
}
